"""matches

Revision ID: 2bce80675b95
Revises: 
Create Date: 2024-08-09 11:02:06.530195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bce80675b95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('team_home', sa.String(), nullable=False),
    sa.Column('team_away', sa.String(), nullable=False),
    sa.Column('score_team_home', sa.Integer(), nullable=False),
    sa.Column('score_team_away', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
